const state={data:null,filters:{search:'',source:'all',sort:'price-asc',fresh:'all'}};
const $=s=>document.querySelector(s);
const money=n=>n==null||n===''?'—':Number(n).toLocaleString('zh-TW')+' 萬';
const val=(v,s='—')=>v==null||v===''?s:v;
function dateText(v){return v?String(v).replace('T',' ').slice(0,16):'—'}
function today(){return state.data.generated_at.slice(0,10)}
function isNew(x){return x['首次出現']===today()&&!x['重新上架日期']}
function isRelisted(x){return x['重新上架日期']===today()}
function sourceMatch(item){return state.filters.source==='all'||String(item['來源網站']||'').includes(state.filters.source)}
function searchMatch(item){const q=state.filters.search.trim().toLowerCase();if(!q)return true;return ['社區名稱','地址','標題','格局'].some(k=>String(item[k]||'').toLowerCase().includes(q))}
function filtered(){let rows=state.data.active.filter(x=>sourceMatch(x)&&searchMatch(x)&&(state.filters.fresh==='all'||isNew(x)));return rows.sort((a,b)=>{if(state.filters.sort==='price-desc')return (b['總價(萬)']||0)-(a['總價(萬)']||0);if(state.filters.sort==='area-desc')return (b['建坪']||0)-(a['建坪']||0);if(state.filters.sort==='updated')return String(b['最後更新']||'').localeCompare(String(a['最後更新']||''));return (a['總價(萬)']||0)-(b['總價(萬)']||0)})}
function renderMetrics(){const d=state.data;const fresh=d.active.filter(isNew).length;const relisted=d.active.filter(isRelisted).length;$('#hero-count').textContent=d.active.length;const m=[['架上物件',d.active.length],['新上架',fresh],['重新上架',relisted],['價格變動',d.price_changes.length]];$('#metrics').innerHTML=m.map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');const callout=$('#new-callout');if(fresh){callout.hidden=false;callout.innerHTML=`<div><strong>今日有 ${fresh} 間新上架</strong><span>優先查看今天首次出現的物件</span></div><button id="new-only" class="new-only ${state.filters.fresh==='new'?'active':''}" type="button">${state.filters.fresh==='new'?'顯示全部架上':'只看新上架'}</button>`;$('#new-only').addEventListener('click',()=>{state.filters.fresh=state.filters.fresh==='new'?'all':'new';renderMetrics();renderListings()})}else{callout.hidden=true;callout.innerHTML=''}}
function renderListings(){const rows=filtered();$('#result-count').textContent=`／ ${rows.length} 筆`;if(!rows.length){$('#listings').innerHTML='<div class="empty">找不到符合條件的物件</div>';return}$('#listings').innerHTML=rows.map(x=>{const fresh=isNew(x),relisted=isRelisted(x),badge=fresh?'<span class="badge badge-new">新上架</span>':relisted?'<span class="badge badge-relisted">重新上架</span>':'';const source=val(x['來源網站']);return `<article class="listing ${fresh?'is-new ':''}${relisted?'is-relisted':''}"><div class="listing-top"><div><div class="listing-title">${val(x['標題'],x['社區名稱'])}</div><div class="community">${val(x['社區名稱'],x['地址'])}・${val(x['行政區'])}</div></div>${badge}</div><div class="price">${money(x['總價(萬)'])} <small>總價</small></div><div class="facts"><div class="fact"><span>建坪</span><strong>${val(x['建坪'])} 坪</strong></div><div class="fact"><span>格局</span><strong>${val(x['格局'])}</strong></div><div class="fact"><span>樓層</span><strong>${val(x['樓層'])}</strong></div><div class="fact"><span>屋齡</span><strong>${val(x['屋齡(年)'])} 年</strong></div><div class="fact"><span>車位</span><strong>${val(x['車位型'])}</strong></div><div class="fact"><span>更新</span><strong>${dateText(x['最後更新'])}</strong></div></div><div class="listing-bottom"><span class="listing-source">來源：${source}</span><a href="${x['來源連結']}" target="_blank" rel="noreferrer">查看房源 →</a><a href="${x['地圖連結']}" target="_blank" rel="noreferrer">地圖 →</a></div></article>`}).join('')}
function renderHistory(){const rows=[...(state.data.price_changes||[]).map(x=>({date:x['日期'],name:x['社區名稱']||'物件',detail:`${x['舊總價(萬)']} → ${x['新總價(萬)']} 萬`,type:'價格變動'})),...(state.data.removed||[]).slice(0,20).map(x=>({date:x['下架日期'],name:x['標題']||x['社區名稱']||'物件',detail:money(x['總價(萬)']),type:'下架'}))].sort((a,b)=>String(b.date).localeCompare(String(a.date)));$('#history').innerHTML=rows.length?rows.map(x=>`<div class="history-row"><span>${dateText(x.date)}</span><strong>${x.name}</strong><span>${x.detail}</span><span>${x.type}</span></div>`).join(''):'<div class="empty">目前沒有變動紀錄</div>'}
function render(){renderMetrics();renderListings();renderHistory();const g=state.data.generated_at;$('#updated').textContent=`資料更新 ${dateText(g)}`;$('#footer-date').textContent=`　最後匯出：${dateText(g)}`}
async function init(){try{state.data=await fetch('data/properties.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('data');return r.json()});render()}catch(e){$('#listings').innerHTML='<div class="empty">資料載入失敗，請稍後重新整理。</div>'}}
$('#search').addEventListener('input',e=>{state.filters.search=e.target.value;renderListings()});$('#source').addEventListener('change',e=>{state.filters.source=e.target.value;renderListings()});$('#sort').addEventListener('change',e=>{state.filters.sort=e.target.value;renderListings()});$('#reset').addEventListener('click',()=>{$('#search').value='';$('#source').value='all';$('#sort').value='price-asc';state.filters={search:'',source:'all',sort:'price-asc',fresh:'all'};renderMetrics();renderListings()});init();
